name: learn_stock_price_lstm
channels:
  - defaults
dependencies:
  - python=3.8.13
  - pip=21.2.2
  - pip:
    - pandas
    - numpy
    - sklearn
    - yfinance
    - plotly
    - keras
    - tensorflow
